version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"   # <- это нужно, чтобы Windows видел Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orgdb
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/orgdb?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  db_data: